### ISSUE TITLE
Type definitions and option to use as hook

### ISSUE THREAD

**Issue by aaronfg** [Tintef/react-native-headphone-detection#3]
Would be nice to have type defs for this and also an option to use it as a hook.  

I wrapped the event listener stuff in a hook for myself and declared my own interface type for the  listener event return value, but it would be nice to not have the linter complain about missing type defs for this module.

In case anyone else is looking for a simple solution here's what I did in my own code:

```ts
// in my hooks file
import HeadphoneDetection from 'react-native-headphone-detection';

export interface IHeadphonesDetectionResult {
  audioJack: boolean;
  bluetooth: boolean;
}

export const useHeadphonesDetection = () => {
  const [result, setResult] = useState<IHeadphonesDetectionResult>({
    audioJack: false,
    bluetooth: false,
  });
  useEffect(() => {
    function _hl(event: IHeadphonesDetectionResult) {
      setResult(event);
    }
    HeadphoneDetection.addListener(_hl);
    return () => {
      if (HeadphoneDetection.remove) {
        HeadphoneDetection.remove();
      }
    };
  });
  return result;
};

// in my components elsewhere
const headphonesDetection = useHeadphonesDetection();
```

This won't silence your linter from complaining about missing typedefs but at least you can use it with type-safety and also as a hook.

**Comment by Tintef** [comment]
@aaronfg That sounds like an awesome plan!

I might be able to add that in 2 or 3 weeks, but I would love to review a PR!
