### ISSUE TITLE
android - USB C headphones not detected

### ISSUE THREAD

**Issue by aaronfg** [Tintef/react-native-headphone-detection#4]
My wired usb c pixel buds and my other generic usb c headphones don't trigger a "true" on the "audioJack" prop. 

Is audioJack literally just the audiojack?

And if so, adding in usb c headphone detection is needed in this module as most android phones are leaving out headphone jacks now in favor of usb c and bt headsets.

This module doesn't work for usb c headsets at the moment.

You might need to add the check for  AudioDeviceInfo.type **TYPE_USB_HEADSET** to your list of **TYPE_WIRED_HEADPHONES** and **TYPE_WIRED_HEADSET**

**Comment by aaronfg** [comment]
I made a PR for this: #5

**Comment by Tintef** [comment]
@aaronfg thanks! The new version (1.1.6) has this new change! 😄
