### ISSUE TITLE
Not working on newer android devices

### ISSUE THREAD

**Issue by MRezaBaiat** [Tintef/react-native-headphone-detection#6]
Hi , the buildconfig file is pretty old and throws errors , please update it to this one to support newer versions

buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.2'
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 28
    buildToolsVersion "28.0.3"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
    }
    lintOptions {
        abortOnError false
    }
}

repositories {
    mavenCentral()
    google()
}

dependencies {
    implementation 'com.facebook.react:react-native:+'
}

**Comment by Tintef** [comment]
Hi! Feel free to submit a PR

**Comment by MRezaBaiat** [comment]
Hello , yes tried to , but apparently you need another branch to pull a PR ?
(sorry not the best to work with github)

**Comment by Tintef** [comment]
@MRezaBaiat You need to fork this repo and then open a PR from that one to this one.

https://opensource.guide/how-to-contribute/#opening-a-pull-request

**Comment by vadympetryshyn** [comment]
Hey, here is PR with update to fix this problem, please merge to master https://github.com/Tintef/react-native-headphone-detection/pull/11

**Comment by vadympetryshyn** [comment]
Could somebody merge my PR?

**Comment by Tintef** [comment]
@vadympetryshyn I'll take a look at it as soon as possible. Hopefully this weekend

**Comment by tushar04** [comment]
@Tintef any update on merge?

**Comment by Tintef** [comment]
@tushar04 I left a comment for @vadympetryshyn, waiting on that

**Comment by vadympetryshyn** [comment]
> @tushar04 I left a comment for @vadympetryshyn, waiting on that

I've tested on android 7 version and all was great

**Comment by Tintef** [comment]
Will publish as soon as I can, hopefully, today or tomorrow
